---
title: "Enunciados"
output:
  pdf_document: default
  html_document: default
date: "2023-10-17"
---

# Problemas Nerea

## Problema 1

Se pide resolver la siguiente tabla de decisión.
$$
\begin{tabular}{c|c|c|c|}
\multicolumn{4}{r}{Estados de la naturaleza} \\
\cline{2-4}
\multirow{3}{*}{Alternativas} & & e1 & e2 \\
\cline{2-4}
 & a1 & 3.000 & -1.000\\
\cline{2-4}
 & a2 & 2.000 & 2.000 \\
\cline{2-4}
\end{tabular}
$$
Se debe resolver con cada uno de los métodos o funciones individuales de Incertidumbre por separado (tanto en situación favorable como desfavorable)

## Problema 2

Pepe es un estudiante que estudia un grado superior en su pueblo natal. Se plantea si cambiarse a un instituto de Sevilla, donde hay mayor cantidad de empresas, en las cuales espera obtener trabajo. Mudarse a Sevilla, le reportaría un coste de 3.000 euros. Sin embargo, si obtiene trabajo (suponiendo que la duración mínima fuera un año, con sueldo de 2000 euros), obtendría un beneficio de 24.000 euros.
Por el contrario, si no se cambia de instituto, no tendría ningún gasto.

Pepe quiere obtener el mayor beneficio de su decisión. Además, en caso de empate, quisiera tener más en cuenta el coste de oportunidad que tienen sus decisiones.

Las dos alternativas posibles para Pepe son:

$$
\begin{itemize}

\item a1= Realizar un cambio de instituto
\item a2= Quedarse en el instituto en el que esta

\end{itemize}


Los dos estados de la naturaleza posibles son:\\

\begin{itemize}

\item a1= Ser contratado
\item a2= No ser contratado

\end{itemize}

La tabla de decisión para este problema seria:

\begin{tabular}{c|c|c|c|}
\multicolumn{4}{r}{Estados de la naturaleza} \\
\cline{2-4}
\multirow{3}{*}{Alternativas} & & Le contraten & No le contraten \\
\cline{2-4}
 & Cambiarse & 21.000 & -3.000\\
\cline{2-4}
 & No cambiarse & -24.000 & 0 \\
\cline{2-4}
\end{tabular}
$$

#Problemas Alba


##Problema 1:

Se pide resolver la siguiente tabla aplicando los criterios de decision bajo incertidumbre tanto en el caso favorable (beneficios), como en el caso desfavorable (costos).

```{r echo=FALSE}

knitr::kable(crea.tablaX(c(30,-5,20,28,20,22,25,-8,5,18,12,14,25,24,0,26),numalternativas=4,numestados=4))

```


##Problema 2: 


Lyre quiere unirse a un gimnasio y ha investigado tres opciones de membresía. Cada membresía tiene sus propias condiciones y costos asociados:

Membresía "Basic Fit": Requiere un pago mensual de 20 euros, pero no cubre todas las instalaciones y clases de gimnasio hasta después de seis meses. Durante los primeros seis meses, solo tiene acceso limitado.

Membresía "Fitness Plus": Ofrece acceso completo a todas las instalaciones y clases desde el primer día, pero con una cuota mensual de 40 euros.

Membresía "Gym Pro": Requiere un pago mensual de 30 euros y cubre todas las instalaciones y clases, excepto las clases de natación.

Lyre planea mantener su membresía de gimnasio durante un año, pero no está segura si usará todas las instalaciones y clases desde el principio debido a su apretado horario en la universidad o si esperará los primeros seis meses antes de hacerlo.

El costo de acceso a las instalaciones y clases de gimnasio es de 15 euros por mes. Si Lyre quiere evaluar el costo total durante el primer año, ¿qué membresía de gimnasio le recomendarías?


